# Generated by Django 5.1.5 on 2025-03-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_shipping_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Pay Now', 'Pay Now'), ('Pay on Delivery', 'Pay on Delivery')], default='Pay on Delivery', max_length=20),
        ),
    ]
